<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    public $guarded= [''];
    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
    public function Comments(){
        return $this->hasMany(Comment::class);
    }
}
